-- Article 7: Brezplačna pravna pomoč v Sloveniji
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'brezplacna-pravna-pomoc-v-sloveniji',
  'Brezplačna pravna pomoč v Sloveniji — kdo je upravičen in kako jo dobiti',
  'Vse o brezplačni pravni pomoči v Sloveniji: pogoji, postopek, telefonsko svetovanje in spletne možnosti. Praktičen vodnik za dostop do pravnega svetovanja brez stroškov.',
  'Pravna pomoč',
  ARRAY[
    'brezplačna pravna pomoč',
    'brezplačna pravna pomoč telefon',
    'odvetniki brezplačna pravna pomoč',
    'pravno svetovanje',
    'brezplačno pravno svetovanje',
    'pravna pomoč brezplačno',
    'brezplačna pravna pomoč slovenija',
    'pravna pomoč za socialno šibke',
    'brezplačen pravni nasvet',
    'pravno svetovanje telefon',
    'pravna klinika',
    'brezplačna pravna pomoč pogoji',
    'kako dobiti brezplačno pravno pomoč',
    'AI pravna pomoč brezplačno'
  ],
  '8 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Ali veste, da vam v Sloveniji pripada brezplačna pravna pomoč, če izpolnjujete določene pogoje? Vsako leto tisoče Slovencev poišče brezplačno pravno svetovanje — pa vendarle mnogi sploh ne vedo, da ta možnost obstaja. V tem članku pojasnjujemo vse poti do brezplačne pravne pomoči: od državne sheme do telefonskega svetovanja in sodobnih AI rešitev."},
    {"type": "heading", "content": "Kaj je brezplačna pravna pomoč?"},
    {"type": "paragraph", "content": "Brezplačna pravna pomoč (BPP) je pravica, ki jo zagotavlja Zakon o brezplačni pravni pomoči (ZBPP). Namenjena je osebam, ki si same ne morejo privoščiti odvetnika, a potrebujejo pravno varstvo. Država v celoti ali delno krije stroške pravnega svetovanja, zastopanja na sodišču in drugih pravnih storitev."},
    {"type": "paragraph", "content": "Pravica do brezplačne pravne pomoči ni omejena samo na državljane Slovenije — upravičene so tudi osebe z dovoljenjem za prebivanje, begunci, prosilci za azil in državljani EU pod določenimi pogoji."},
    {"type": "heading", "content": "Kdo je upravičen do brezplačne pravne pomoči?"},
    {"type": "paragraph", "content": "Kako preverite, ali ste upravičeni? Glavni pogoj je finančni — vaš mesečni dohodek in premoženje ne smeta presegati zakonsko določenega praga. Okrajno sodišče pri odločanju upošteva več dejavnikov."},
    {"type": "list", "content": "Pogoji za pridobitev BPP:", "items": ["Mesečni dohodek prosilca ne presega dvakratnika osnovnega zneska minimalnega dohodka", "Premoženje prosilca (nepremičnine, vozila, prihranki) ne presega zakonsko določenega praga", "Zadeva ni očitno nerazumna — mora imeti razumne možnosti za uspeh", "Prosilec ne more sam kriti stroškov pravnega postopka brez ogrožanja lastnega preživljanja"]},
    {"type": "heading", "content": "Kako zaprositi za brezplačno pravno pomoč"},
    {"type": "paragraph", "content": "Postopek je relativno preprost. Vlogo oddate na okrajnem sodišču, pristojnem za vaše prebivališče. Potrebujete izpolnjen obrazec, dokazila o finančnem stanju (plačilne liste, bančni izpiski, odločba o socialnih transferjih) in opis pravne zadeve."},
    {"type": "list", "content": "Koraki za pridobitev BPP:", "items": ["Obiščite okrajno sodišče ali prenesite obrazec s spleta (sodisce.si)", "Izpolnite vlogo za dodelitev brezplačne pravne pomoči", "Priložite dokazila o dohodku in premoženju", "Opišite pravno zadevo, za katero potrebujete pomoč", "Sodišče odloči v 15 dneh — v nujnih primerih v 3 dneh"]},
    {"type": "heading", "content": "Brezplačna pravna pomoč po telefonu"},
    {"type": "paragraph", "content": "Ali potrebujete hiter pravni nasvet po telefonu? V Sloveniji deluje več organizacij, ki ponujajo brezplačno telefonsko pravno svetovanje. To je odlična prva stopnja, če niste prepričani, ali sploh potrebujete odvetnika."},
    {"type": "list", "content": "Brezplačno telefonsko svetovanje:", "items": ["Pravno-informacijski center (PIC) — brezplačno svetovanje za ranljive skupine", "Pravna klinika Pravne fakultete v Ljubljani — brezplačno svetovanje študentov pod nadzorom profesorjev", "Zveza potrošnikov Slovenije — brezplačna pomoč za potrošniške spore", "Varuh človekovih pravic — pomoč pri kršitvah temeljnih pravic", "Društvo za nenasilno komunikacijo — pravna pomoč za žrtve nasilja"]},
    {"type": "heading", "content": "Spletno pravno svetovanje z AI"},
    {"type": "paragraph", "content": "Kako hitro dobiti pravni nasvet, ne da bi čakali na termin? Sodobna tehnologija omogoča takojšen dostop do pravnih informacij. AI pravni svetovalci, kot je AI-Odvetnik, vam na podlagi slovenskega prava v nekaj sekundah podajo razlago vaše situacije, opozorijo na ključne zakonske določbe in predlagajo naslednje korake."},
    {"type": "paragraph", "content": "AI pravno svetovanje ni nadomestilo za odvetnika, je pa odlična prva stopnja: razumete svoje pravice, se pripravite na posvet z odvetnikom in prihranite čas ter denar. Brezplačen paket vam omogoča več poizvedb na dan — brez obveznosti."},
    {"type": "cta", "content": "Potrebujete hiter pravni nasvet? AI-Odvetnik vam brezplačno pojasni vaše pravice v nekaj sekundah."},
    {"type": "heading", "content": "Kdaj brezplačna pravna pomoč ni dovolj?"},
    {"type": "paragraph", "content": "Kdaj potrebujete pravega odvetnika? Brezplačna pravna pomoč in AI svetovanje sta odlična za razumevanje situacije, a za zastopanje na sodišču, sestavo zahtevnih pogodb ali obrambo v kazenskem postopku potrebujete kvalificiranega odvetnika. V teh primerih je državna BPP neprecenljiva — krije tudi stroške zastopanja."},
    {"type": "list", "content": "Za te zadeve priporočamo odvetnika:", "items": ["Zastopanje na sodišču (pravdni, kazenski, upravni postopki)", "Sestava zapletenih pogodb (nepremičnine, podjetja)", "Dedovanje z več dediči ali spornimi oporokami", "Kazenski postopki in priporni naroki", "Spori z delodajalcem, ki zahtevajo tožbo"]},
    {"type": "heading", "content": "Pogosta vprašanja"},
    {"type": "paragraph", "content": "Ali je brezplačna pravna pomoč res brezplačna? Da, če vam jo sodišče odobri, vam država krije vse stroške — od svetovanja do zastopanja. Če zadevo izgubite, vam običajno ni treba vračati stroškov (razen v izjemnih primerih)."},
    {"type": "paragraph", "content": "Koliko časa traja postopek odobritve? Sodišče mora odločiti v 15 dneh od prejema popolne vloge. V nujnih zadevah (npr. priporni narok) je rok le 3 dni."},
    {"type": "paragraph", "content": "Ali lahko izberem svojega odvetnika? Da, pri vlogi za BPP lahko predlagate odvetnika po lastni izbiri. Če tega ne storite, vam ga dodeli sodišče."},
    {"type": "quote", "content": "Pravica do pravne pomoči ni privilegij premožnih — je temeljna pravica vsakega posameznika. Izkoristite vse možnosti, ki vam jih ponuja sistem."}
  ]'::jsonb
);

-- Article 8: Kupoprodajna pogodba
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'kupoprodajna-pogodba-vse-kar-morate-vedeti',
  'Kupoprodajna pogodba — kaj mora vsebovati, vzorec in napake',
  'Kaj je kupoprodajna pogodba, kaj mora vsebovati, kako jo sestaviti za avto ali nepremičnino. Pogoste napake, pravice kupca in prodajalca ter vloga notarja.',
  'Pogodbe',
  ARRAY[
    'kupoprodajna pogodba',
    'kupoprodajna pogodba vzorec',
    'kupoprodajna pogodba za avto',
    'kupoprodajna pogodba nepremičnina',
    'kupoprodajna pogodba amzs',
    'amzs kupoprodajna pogodba',
    'kupoprodajna pogodba vsebina',
    'sestavitev kupoprodajne pogodbe',
    'kupoprodajna pogodba za vozilo',
    'pogodba o prodaji nepremičnine',
    'kupoprodajna pogodba cena',
    'kupoprodajna pogodba za stanovanje',
    'kupoprodajna pogodba notarski zapis'
  ],
  '9 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Kupoprodajna pogodba je najpogostejša vrsta pogodbe v vsakdanjem življenju — od nakupa avtomobila do stanovanja. Kljub temu mnogi ne vedo, kaj mora pogodba vsebovati, kdaj potrebujete notarsko overitev in katere napake vas lahko stanejo tisoče evrov. V tem vodniku razložimo vse, kar morate vedeti."},
    {"type": "heading", "content": "Kaj je kupoprodajna pogodba?"},
    {"type": "paragraph", "content": "Kupoprodajna pogodba je dvostranska pogodba, s katero se prodajalec zavezuje, da bo kupcu izročil stvar in mu prenesel lastninsko pravico, kupec pa se zavezuje, da bo plačal kupnino. Ureja jo Obligacijski zakonik (OZ) v členih 435 do 527."},
    {"type": "paragraph", "content": "Pogodba je sklenjena, ko se stranki dogovorita o bistvenih sestavinah — predmetu prodaje in kupnini. Za premičnine (avto, pohištvo, elektronika) zadostuje ustna pogodba, za nepremičnine pa je obvezna pisna oblika."},
    {"type": "heading", "content": "Kupoprodajna pogodba za avtomobil"},
    {"type": "paragraph", "content": "Kako sestaviti kupoprodajno pogodbo za avto? Prodaja avtomobila je najpogostejši primer, kjer ljudje potrebujejo kupoprodajno pogodbo. AMZS ponuja standardni obrazec, a vseeno morate paziti na več stvari."},
    {"type": "list", "content": "Bistvene sestavine pogodbe za avto:", "items": ["Podatki o prodajalcu in kupcu (ime, naslov, EMŠO ali davčna številka)", "Podatki o vozilu (znamka, model, letnik, VIN številka, registrska oznaka)", "Kupnina in način plačila (gotovina, nakazilo, obročno)", "Izjava prodajalca o stanju vozila (kilometri, poškodbe, napake)", "Datum in kraj izročitve vozila", "Izjava o prenosu lastništva in obveznosti prepisa"]},
    {"type": "paragraph", "content": "Ali je AMZS pogodba dovolj? Za enostavne prodaje med zasebniki ja. Pri dražjih vozilih ali kadar slutite težave (prikrit kilometri, skrite napake) pa se splača pogodbo pregledati ali jo dopolniti z dodatnimi garancijami."},
    {"type": "heading", "content": "Kupoprodajna pogodba za nepremičnino"},
    {"type": "paragraph", "content": "Prodaja nepremičnine je bistveno bolj kompleksna od prodaje avta. Pogodba mora biti v pisni obliki, podpis prodajalca pa mora biti notarsko overjen za vpis v zemljiško knjigo."},
    {"type": "list", "content": "Kaj mora vsebovati pogodba za nepremičnino:", "items": ["Natančen opis nepremičnine (katastrska občina, parcelna številka, ID stavbe)", "Kupnina, rok plačila in način (bančna garancija, fiduciarni račun)", "Zemljiškoknjižno dovolilo (intabulacijska klavzula) za prenos lastništva", "Izjava prodajalca o bremen (hipoteke, služnosti, prepovedi odtujitve)", "Rok izročitve nepremičnine in pogodbena kazen za zamudo", "Določila o stvarnih napakah in jamčevanju"]},
    {"type": "paragraph", "content": "Kdaj potrebujete notarski zapis? Za prodajo nepremičnin notarski zapis ni obvezen (zadostuje overjen podpis), a je priporočljiv — notar preveri pravno stanje, zagotovi varnost obeh strank in poskrbi za davčni vidik."},
    {"type": "heading", "content": "Pravice kupca pri napakah na stvari"},
    {"type": "paragraph", "content": "Kaj storiti, če kupljena stvar ni takšna, kot je bilo dogovorjeno? Obligacijski zakonik vam daje več pravic pri stvarnih in pravnih napakah. Stvarna napaka pomeni, da stvar nima lastnosti, ki so bile dogovorjene ali pričakovane."},
    {"type": "list", "content": "Pravice kupca pri napakah:", "items": ["Zahteva za odpravo napake (popravilo)", "Znižanje kupnine sorazmerno z napako", "Zamenjava stvari z brezhibno (pri generičnih stvareh)", "Odstop od pogodbe in vrnitev kupnine (pri bistvenih napakah)", "Povrnitev škode, ki je nastala zaradi napake"]},
    {"type": "paragraph", "content": "Kako dolgo lahko uveljavljate napake? Kupec mora prodajalca o napaki obvestiti v dveh mesecih od odkritja. Pravica do uveljavljanja napak zastara v dveh letih od izročitve stvari (pri nepremičninah v treh letih)."},
    {"type": "heading", "content": "Pogoste napake pri kupoprodajni pogodbi"},
    {"type": "list", "content": "Na te napake bodite pozorni:", "items": ["Pomanjkljiv opis predmeta — brez VIN številke, parcelne številke ali natančnih specifikacij", "Nejasno določena kupnina — brez valute, roka plačila ali posledic neplačila", "Manjkajoče zemljiškoknjižno dovolilo — brez njega ne morete vpisati lastništva", "Brez izjave o bremenih — kupite nepremičnino s hipoteko, za katero niste vedeli", "Brez določil o napakah — odpovedujete se pravicam, ne da bi to vedeli", "Ustna pogodba za nepremičnino — je nična in neveljavna"]},
    {"type": "cta", "content": "Pred podpisom pogodbe preverite, ali ste ustrezno zaščiteni. AI-Odvetnik vam pomaga razumeti pogodbo in opozori na tveganja."},
    {"type": "heading", "content": "Koliko stane sestavitev kupoprodajne pogodbe?"},
    {"type": "paragraph", "content": "Koliko stane sestavitev pogodbe? Za avto lahko uporabite brezplačen AMZS obrazec. Za nepremičnine se cene gibljejo: odvetniku za sestavitev pogodbe boste plačali 200–800 EUR, notarski zapis pa stane 100–500 EUR, odvisno od vrednosti nepremičnine."},
    {"type": "quote", "content": "Kupoprodajna pogodba je temelj vsake transakcije. Vzemite si čas za pregled — nekaj ur vloženega časa vam lahko prihrani mesece zapletov."}
  ]'::jsonb
);

-- Article 9: Podjemna pogodba
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'podjemna-pogodba-vodnik',
  'Podjemna pogodba — kdaj jo potrebujete in kako jo sestaviti',
  'Vse o podjemni pogodbi: razlika s pogodbo o zaposlitvi, obvezne sestavine, pravice in obveznosti podjemnika ter naročnika. Kdaj je podjemna pogodba zakonita in kdaj gre za prikrito delovno razmerje.',
  'Pogodbe',
  ARRAY[
    'podjemna pogodba',
    'podjemna pogodba vzorec',
    'podjemna pogodba davki',
    'podjemna pogodba sp',
    'podjemna pogodba ali zaposlitev',
    'podjemna pogodba obveznosti',
    'podjemna pogodba za delo',
    'podjemna pogodba razlika',
    'podjemna pogodba odmor',
    'podjemna pogodba študent',
    'prikrito delovno razmerje',
    'pogodba civilnega prava',
    'podjemna pogodba prispevki'
  ],
  '8 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Podjemna pogodba je ena najpogostejših pogodb civilnega prava v Sloveniji — in hkrati ena najbolj zlorabljenih. Kdaj je sklenitev podjemne pogodbe zakonita, kdaj gre za prikrito delovno razmerje in kakšne so davčne posledice? V tem članku razložimo vse, kar morate vedeti kot naročnik ali podjemnik."},
    {"type": "heading", "content": "Kaj je podjemna pogodba?"},
    {"type": "paragraph", "content": "Podjemna pogodba (pogodba o delu) je pogodba, s katero se podjemnik (izvajalec) zavezuje opraviti določen posel — izdelati ali popraviti stvar, opraviti fizično ali umsko delo — naročnik pa se zavezuje plačati dogovorjeno plačilo. Ureja jo Obligacijski zakonik v členih 619 do 648."},
    {"type": "paragraph", "content": "Kako se podjemna pogodba razlikuje od pogodbe o zaposlitvi? Ključna razlika je v naravi razmerja: pri podjemni pogodbi gre za enkratno naročilo z dogovorjenim rezultatom, pri zaposlitvi pa za trajno opravljanje dela pod nadzorom delodajalca."},
    {"type": "heading", "content": "Razlika med podjemno pogodbo in pogodbo o zaposlitvi"},
    {"type": "list", "content": "Podjemna pogodba — značilnosti:", "items": ["Podjemnik sam organizira delo (čas, kraj, način)", "Dogovorjen je končni rezultat, ne proces dela", "Ni podrejenosti — naročnik ne daje navodil o načinu dela", "Podjemnik dela z lastnimi sredstvi in orodji", "Plačilo je vezano na rezultat, ne na delovni čas", "Ni pravice do dopusta, bolniške ali odpravnine"]},
    {"type": "list", "content": "Pogodba o zaposlitvi — značilnosti:", "items": ["Delavec dela po navodilih in pod nadzorom delodajalca", "Delo se opravlja v prostorih in z sredstvi delodajalca", "Določen delovni čas in obvezna prisotnost", "Pravica do dopusta, bolniške, odpravnine in vseh socialnih pravic", "Plačilo je mesečna plača, neodvisno od rezultata", "Odpoved le po zakonsko določenem postopku"]},
    {"type": "heading", "content": "Kdaj je podjemna pogodba prikrito delovno razmerje?"},
    {"type": "paragraph", "content": "Ali vaša podjemna pogodba morda prikriva delovno razmerje? To je v Sloveniji pogost problem. Če podjemnik dela vsak dan od 8 do 16 v prostorih naročnika, uporablja naročnikova orodja in prejema navodila o načinu dela — verjetno gre za prikrito delovno razmerje, ne glede na to, kako je pogodba poimenovana."},
    {"type": "list", "content": "Znaki prikritega delovnega razmerja:", "items": ["Delo se opravlja dlje časa (več mesecev ali let) kontinuirano", "Naročnik določa delovni čas in kraj dela", "Podjemnik uporablja opremo in prostore naročnika", "Naročnik daje podrobna navodila o načinu opravljanja dela", "Podjemnik ne sme delo opravljati za druge naročnike", "Plačilo je mesečno in fiksno, ne vezano na rezultat"]},
    {"type": "paragraph", "content": "Kakšne so posledice? Delavec lahko kadarkoli zahteva ugotovitev obstoja delovnega razmerja na sodišču. Delodajalcu grozi plačilo vseh prispevkov za nazaj, globe inšpektorata (2.000–20.000 EUR) in obveznost sklenitve pogodbe o zaposlitvi."},
    {"type": "heading", "content": "Obvezne sestavine podjemne pogodbe"},
    {"type": "list", "content": "Dobra podjemna pogodba mora vsebovati:", "items": ["Stranki pogodbe (naročnik in podjemnik s polnimi podatki)", "Natančen opis posla oziroma dela, ki ga podjemnik opravi", "Rok za dokončanje dela", "Višina plačila in rok plačila", "Materiali — kdo jih zagotovi (naročnik ali podjemnik)", "Odgovornost za napake na delu (jamčevanje)", "Pogoji za odstop od pogodbe", "Zavarovanje in odgovornost za škodo"]},
    {"type": "heading", "content": "Davki in prispevki pri podjemni pogodbi"},
    {"type": "paragraph", "content": "Koliko davkov plačate pri podjemni pogodbi? Davčna obremenitev je eden ključnih razlogov, zakaj se naročniki odločajo za podjemno pogodbo — a prihranek ni tako velik, kot si mnogi mislijo."},
    {"type": "list", "content": "Davčne obveznosti:", "items": ["Akontacija dohodnine: 25% od davčne osnove", "Prispevki za socialno varnost: približno 15,5% bremeni naročnika", "Normirani stroški: podjemnik lahko uveljavlja 10% normiranih stroškov", "Podjemnik nima pravice do bolniške, dopusta ali pokojninskega staža v polnem obsegu"]},
    {"type": "paragraph", "content": "Kaj pa s.p.? Če podjemnik opravlja delo kot samostojni podjetnik (s.p.), se obdavčitev razlikuje. Naročnik plača bruto dogovorjeni znesek, s.p. pa sam obračuna davke in prispevke. To je pogosto ugodnejše za obe strani."},
    {"type": "heading", "content": "Podjemna pogodba za študenta"},
    {"type": "paragraph", "content": "Ali lahko študent dela po podjemni pogodbi? Da, a je v večini primerov študentsko delo (prek študentskega servisa) ugodnejša možnost. Podjemna pogodba za študenta pomeni plačilo vseh prispevkov, kar je dražje za naročnika in manj ugodno za študenta."},
    {"type": "cta", "content": "Niste prepričani, ali je vaša pogodba pravilno sestavljena? AI-Odvetnik vam pomaga preveriti skladnost s slovenskim pravom."},
    {"type": "heading", "content": "Najpogostejše napake"},
    {"type": "list", "content": "Izogibajte se tem napakam:", "items": ["Preširok opis dela, ki dejansko opisuje delovno razmerje", "Brez roka za dokončanje — pogodba izgubi značaj enkratnega posla", "Brez določil o odgovornosti za napake", "Plačilo po urah namesto za rezultat — znak delovnega razmerja", "Klavzula o ekskluzivnosti — podjemnik ne sme delati za druge"]},
    {"type": "quote", "content": "Podjemna pogodba je odlična za enkratne projekte in specializirana dela. A če razmerje izgleda kot zaposlitev, ga sodišče lahko tudi tako obravnava — ne glede na ime pogodbe."}
  ]'::jsonb
);

-- Article 10: Odškodnine — kako do pravičnega nadomestila
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'odskodnine-kako-do-pravicnega-nadomestila',
  'Odškodnine v Sloveniji — kako uveljavljati odškodninski zahtevek',
  'Kako uveljavljati odškodnino v Sloveniji: prometne nesreče, poškodbe pri delu, zdravniške napake. Pogoji, roki, višina odškodnin in izbira odvetnika za odškodnine.',
  'Odškodnine',
  ARRAY[
    'odškodnina',
    'odvetnik za odškodnine',
    'najboljši odvetnik za odškodnine',
    'odvetnik za odškodnine forum',
    'odškodninski zahtevek',
    'odškodnina za prometno nesrečo',
    'odškodnina za poškodbo pri delu',
    'odškodnina za bolečine',
    'višina odškodnine',
    'odškodnina za nepremoženjsko škodo',
    'odškodnina zastaranje',
    'kako dobiti odškodnino',
    'odškodnina zavarovalnica',
    'odškodnina za zdravniško napako'
  ],
  '9 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Ste utrpeli poškodbo v prometni nesreči, pri delu ali zaradi zdravniške napake? V Sloveniji imate pravico do odškodnine — a postopek je pogosto zapleten, zavarovalnice pa ponujajo prenizke zneske. V tem članku razložimo, kako uveljavljati odškodninski zahtevek, kakšne odškodnine lahko pričakujete in kako izbrati pravega odvetnika za odškodnine."},
    {"type": "heading", "content": "Kdaj imate pravico do odškodnine?"},
    {"type": "paragraph", "content": "Odškodninska odgovornost v Sloveniji temelji na Obligacijskem zakoniku. Za uspešen odškodninski zahtevek morate dokazati štiri pogoje — če katerikoli manjka, zahtevek ne bo uspel."},
    {"type": "list", "content": "Štirje pogoji za odškodnino:", "items": ["Protipravno ravnanje — nekdo je kršil pravno normo ali dolžnost skrbnosti", "Škoda — nastala vam je premoženjska ali nepremoženjska škoda", "Vzročna zveza — škoda je neposredna posledica protipravnega ravnanja", "Krivda — povzročitelj je ravnal naklepno ali malomarno (razen pri objektivni odgovornosti)"]},
    {"type": "heading", "content": "Vrste odškodnin"},
    {"type": "paragraph", "content": "Kako visoka je lahko odškodnina? Slovensko pravo razlikuje med premoženjsko in nepremoženjsko škodo. Skupaj tvorita celotno odškodnino — pravico imate do obeh."},
    {"type": "list", "content": "Premoženjska škoda:", "items": ["Stroški zdravljenja in rehabilitacije", "Izgubljeni zaslužek med odsotnostjo z dela", "Zmanjšana delovna sposobnost (renta)", "Stroški popravila ali zamenjave poškodovane stvari", "Stroški najema nadomestnega vozila"]},
    {"type": "list", "content": "Nepremoženjska škoda (bolečnine):", "items": ["Telesne bolečine in nevšečnosti med zdravljenjem", "Duševne bolečine zaradi zmanjšanja življenjskih aktivnosti", "Duševne bolečine zaradi skaženosti", "Strah (pretekli in prihodnji)", "Duševne bolečine zaradi smrti bližnjega"]},
    {"type": "heading", "content": "Odškodnina za prometno nesrečo"},
    {"type": "paragraph", "content": "Kako uveljavljati odškodnino po prometni nesreči? Prometne nesreče so najpogostejši razlog za odškodninske zahtevke. Odškodnino uveljavljate pri zavarovalnici povzročitelja (AO zavarovanje). Če zavarovalnica zavrne zahtevek ali ponudi prenizek znesek, se obrnete na sodišče."},
    {"type": "list", "content": "Koraki po prometni nesreči:", "items": ["Takoj pokličite policijo in zagotovite zdravniški pregled", "Dokumentirajte poškodbe — fotografije, zdravniška dokumentacija", "Prijavite škodo zavarovalnici povzročitelja v 15 dneh", "Zavarovalnica mora odgovoriti v 60 dneh (pri telesnih poškodbah v 90 dneh)", "Če ponudba ni sprejemljiva, angažirajte odvetnika za odškodnine", "Po potrebi vložite tožbo — zastaralni rok je 3 leta"]},
    {"type": "heading", "content": "Odškodnina za poškodbo pri delu"},
    {"type": "paragraph", "content": "Ali ste se poškodovali na delovnem mestu? Delodajalec odgovarja za škodo, ki nastane delavcu pri delu ali v zvezi z delom. Odškodninski zahtevek lahko uveljavljate neposredno proti delodajalcu ali pri njegovi zavarovalnici (če ima sklenjeno zavarovanje odgovornosti)."},
    {"type": "paragraph", "content": "Koliko znaša odškodnina za poškodbo pri delu? Višina je odvisna od teže poškodbe. Za lažje poškodbe (zlom roke, izvin) sodišča prisojajo 2.000–10.000 EUR, za hujše (trajne posledice, invalidnost) pa 20.000–100.000 EUR ali več."},
    {"type": "heading", "content": "Odškodnina za zdravniško napako"},
    {"type": "paragraph", "content": "Kako dokazati zdravniško napako? Zdravniki odgovarjajo za škodo, če so ravnali v nasprotju s pravili medicinske stroke. Dokazovanje je zahtevno — potrebujete medicinsko dokumentacijo in pogosto izvedensko mnenje."},
    {"type": "paragraph", "content": "Odškodnino za zdravniško napako uveljavljate proti zdravstvenemu zavodu. Pred tožbo je smiselno vložiti zahtevek na bolnišnico ali zdravstveni dom. Rok zastaranja je 3 leta od odkritja škode."},
    {"type": "heading", "content": "Kako izbrati odvetnika za odškodnine"},
    {"type": "paragraph", "content": "Kako najdem najboljšega odvetnika za odškodnine? Izbira pravega odvetnika je ključna za uspeh. Iščite odvetnika, ki se specializira za odškodninsko pravo in ima izkušnje s primeri, podobnimi vašemu."},
    {"type": "list", "content": "Na kaj paziti pri izbiri odvetnika:", "items": ["Specializacija — iščite odvetnika z izkušnjami na odškodninskem področju", "Reference — vprašajte za primere, ki jih je uspešno rešil", "Način plačila — nekateri odvetniki delajo na uspeh (provizija od dosežene odškodnine)", "Komunikacija — odvetnik mora biti dosegljiv in razumljiv", "Transparentnost — vnaprej se dogovorite o stroških in pričakovanjih", "Ne nasedajte forumskim priporočilom — preverite dejanske izkušnje"]},
    {"type": "cta", "content": "Niste prepričani, ali imate pravico do odškodnine? AI-Odvetnik vam brezplačno pomaga oceniti vašo situacijo."},
    {"type": "heading", "content": "Zastaralni roki za odškodnine"},
    {"type": "paragraph", "content": "Kdaj zastara pravica do odškodnine? Pravočasno ukrepanje je ključno — po poteku zastaralnega roka izgubite pravico do uveljavljanja zahtevka."},
    {"type": "list", "content": "Zastaralni roki:", "items": ["Splošni rok: 3 leta od dneva, ko ste izvedeli za škodo in povzročitelja", "Objektivni rok: 5 let od nastanka škode (ne glede na vedenje)", "Kaznivo dejanje: če je škoda posledica kaznivega dejanja, velja zastaralni rok za kazenski pregon (pogosto 10+ let)", "Zavarovalnica: zahtevek proti zavarovalnici zastara v 3 letih"]},
    {"type": "quote", "content": "Ne sprejemajte prve ponudbe zavarovalnice — pogosto je bistveno nižja od tistega, kar vam pripada. Posvetujte se z odvetnikom, preden karkoli podpišete."}
  ]'::jsonb
);

-- Article 11: Posojilna pogodba
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'posojilna-pogodba-kako-zavarujete-denar',
  'Posojilna pogodba — kako zavarujete posojeni denar',
  'Vse o posojilni pogodbi: obvezne sestavine, obresti, zavarovanje vračila in pogoste napake. Kako pravilno posoditi denar prijatelju, sorodniku ali poslovnemu partnerju.',
  'Pogodbe',
  ARRAY[
    'posojilna pogodba',
    'posojilna pogodba vzorec',
    'posojilna pogodba med fizičnimi osebami',
    'posojilna pogodba obresti',
    'posojilna pogodba zavarovanje',
    'pogodba o posojilu denarja',
    'posojilna pogodba brez obresti',
    'kako posoditi denar',
    'posojilna pogodba rok vračila',
    'posojilo med prijatelji pogodba',
    'posojilna pogodba izvršba',
    'posojilna pogodba davek',
    'posojilna pogodba notarski zapis'
  ],
  '7 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Posoditi denar prijatelju, sorodniku ali znancu je pogost pojav — a brez ustrezne pogodbe je to eden najpogostejših razlogov za uničene odnose in izgubljen denar. Posojilna pogodba vas zaščiti in zagotovi, da bo posojeni denar vrnjen. V tem članku razložimo, kako jo pravilno sestaviti."},
    {"type": "heading", "content": "Kaj je posojilna pogodba?"},
    {"type": "paragraph", "content": "Posojilna pogodba je pogodba, s katero posojilodajalec izroči posojilojemalcu določen znesek denarja ali nadomestnih stvari, posojilojemalec pa se zaveže, da bo enak znesek vrnil po določenem času. Ureja jo Obligacijski zakonik v členih 569 do 582."},
    {"type": "paragraph", "content": "Ali je ustna pogodba veljavna? Da, posojilna pogodba je veljavna tudi v ustni obliki. Ampak — brez pisnega dokaza je v primeru spora praktično nemogoče dokazati, da ste denar posodili, koliko in pod kakšnimi pogoji. Vedno sklenite pisno pogodbo."},
    {"type": "heading", "content": "Obvezne sestavine posojilne pogodbe"},
    {"type": "list", "content": "Dobra posojilna pogodba mora vsebovati:", "items": ["Stranki pogodbe — polna imena, naslovi, EMŠO ali davčne številke", "Znesek posojila — natančen znesek v evrih, zapisan s številko in besedo", "Način izročitve — gotovina (s potrdilom o prevzemu) ali nakazilo na račun", "Rok vračila — natančen datum ali dogodek, ki sproži obveznost vračila", "Obresti — ali se zaračunavajo, koliko in kako (letna obrestna mera)", "Način vračila — enkratno, v obrokih, mesečno", "Posledice zamude — zamudne obresti, takojšnja zapadlost celotnega dolga", "Zavarovanje — poroštvo, zastava premičnin ali nepremičnin, menica", "Podpisa obeh strank in datum"]},
    {"type": "heading", "content": "Obresti pri posojilni pogodbi"},
    {"type": "paragraph", "content": "Ali lahko zaračunate obresti? Da, a z omejitvami. Slovensko pravo razlikuje med pogodbami med fizičnimi osebami in gospodarskimi pogodbami."},
    {"type": "list", "content": "Pravila o obrestih:", "items": ["Med fizičnimi osebami: obresti morajo biti izrecno dogovorjene — brez dogovora posojilo ni obrestovano", "Med gospodarskimi subjekti: posojilo je obrestovano tudi brez izrecnega dogovora", "Najvišja dovoljena obrestna mera: zakonske zamudne obresti (trenutno 10,5% letno) — višje obresti so oderuške in nične", "Prepoved obrestnih obresti (anatocizem): obresti na obresti niso dovoljene med fizičnimi osebami", "Posojilo brez obresti: davčno se lahko šteje kot darilo — pri višjih zneskih preverite davčne posledice"]},
    {"type": "heading", "content": "Kako zavarovati vračilo posojila?"},
    {"type": "paragraph", "content": "Kako zagotovite, da boste denar dobili nazaj? Pisna pogodba je prvi korak, a obstajajo dodatni mehanizmi zavarovanja, ki bistveno povečajo vaše možnosti za izterjavo."},
    {"type": "list", "content": "Načini zavarovanja posojila:", "items": ["Poroštvo — tretja oseba (porok) se zaveže plačati, če dolžnik ne vrne posojila", "Zastava premičnin — dolžnik vam v zastavo izroči vrednostni predmet (avto, nakit)", "Hipoteka — zastava nepremičnine, vpisana v zemljiško knjigo", "Menica — hitrejša izvršba brez sodnega postopka", "Notarski zapis z neposredno izvršljivostjo — omogoča izvršbo brez tožbe", "Cesija terjatev — dolžnik vam odstopi svoje terjatve do tretjih oseb"]},
    {"type": "paragraph", "content": "Kaj je notarski zapis z neposredno izvršljivostjo? To je najmočnejše zavarovanje. Če dolžnik ne vrne posojila, lahko na podlagi notarskega zapisa takoj vložite predlog za izvršbo — brez tožbe in brez dolgotrajnega sodnega postopka. Stane 50–200 EUR, a vam lahko prihrani leta čakanja."},
    {"type": "heading", "content": "Posojilo med prijatelji in sorodniki"},
    {"type": "paragraph", "content": "Kako posoditi denar prijatelju, ne da bi uničili odnos? Prav pri posojilih bližnjim je pogodba najpomembnejša — jasni dogovori preprečujejo nesporazume."},
    {"type": "list", "content": "Nasveti za posojilo bližnjim:", "items": ["Vedno sklenite pisno pogodbo — tudi za manjše zneske", "Posodite le toliko, kolikor si lahko privoščite izgubiti", "Jasno določite rok vračila — brez nejasnosti", "Denar nakažite na račun — tako imate dokaz o izročitvi", "Ne mešajte čustev s financami — pogodba je zaščita za oba", "Če gre za večji znesek, razmislite o notarskem zapisu"]},
    {"type": "heading", "content": "Davčni vidik posojila"},
    {"type": "paragraph", "content": "Ali morate prijaviti posojilo davčnemu uradu? Samo posojilo ni obdavčeno, a morajo biti obresti prijavljene kot dohodek. Posojilo brez obresti med sorodniki se lahko davčno obravnava kot darilo — pri zneskih nad 5.000 EUR je priporočljivo preveriti davčne posledice."},
    {"type": "cta", "content": "Potrebujete pomoč pri sestavitvi posojilne pogodbe? AI-Odvetnik vam pojasni vaše pravice in opozori na ključne klavzule."},
    {"type": "heading", "content": "Kaj storiti, če dolžnik ne vrne posojila?"},
    {"type": "list", "content": "Koraki za izterjavo:", "items": ["Pisni opomin dolžniku s pozivom k plačilu in rokom", "Mediacija — poskusite sporazumno rešitev pred sodiščem", "Tožba na sodišču — z dokazili (pogodba, potrdilo o nakazilu, opomini)", "Izvršba — po pravnomočni sodbi zahtevajte rubež plače, računa ali premoženja", "Zastaranje: pravica do izterjave zastara v 5 letih od zapadlosti (10 let za gospodarsko posojilo)"]},
    {"type": "quote", "content": "Najboljše posojilo je tisto, ki ga spremlja jasna pogodba. Pet minut za podpis danes vam lahko prihrani pet let sodnega postopka jutri."}
  ]'::jsonb
);
