-- Article 2: Koliko stane odvetnik
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'koliko-stane-odvetnik-v-sloveniji',
  'Koliko stane odvetnik v Sloveniji v 2026 — cenik, tarifa in nasveti',
  'Pregled cen odvetniških storitev v Sloveniji: koliko stane ura odvetnika, posvet, zastopanje na sodišču, ločitev, dedovanje in sestavitev pogodbe. Primerjava stroškov in cenejše alternative.',
  'Stroški',
  ARRAY[
    'koliko stane odvetnik',
    'koliko stane ura odvetnika',
    'koliko stane posvet pri odvetniku',
    'cena odvetnika',
    'pravni nasvet cena',
    'cena odvetnika za ločitev',
    'cena odvetnika za dedovanje',
    'odvetniška tarifa',
    'odvetniška tarifa 2026',
    'stroški odvetnika',
    'cena pravnega svetovanja',
    'koliko stane odvetnik za ločitev',
    'koliko stane sestavitev pogodbe',
    'koliko stane pravni nasvet',
    'cenovno ugoden odvetnik',
    'AI odvetnik cena',
    'brezplačna pravna pomoč'
  ],
  '7 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Eden najpogostejših razlogov, zakaj se ljudje izogibajo pravni pomoči, je strah pred visokimi stroški. Koliko pravzaprav stane odvetnik v Sloveniji? V tem članku pregledamo odvetniško tarifo, okvirne cene za najpogostejše pravne storitve in vam pokažemo, kako lahko prihranite pri pravnem svetovanju."},
    {"type": "heading", "content": "Odvetniška tarifa v Sloveniji"},
    {"type": "paragraph", "content": "Cene odvetniških storitev v Sloveniji ureja odvetniška tarifa, ki jo določa Odvetniška zbornica Slovenije. Tarifa predpisuje minimalne in maksimalne zneske za posamezne storitve. Odvetnik vam mora pred začetkom dela jasno povedati, koliko bo storitev stala, ali pa z vami skleniti pisno pogodbo o nagradi."},
    {"type": "paragraph", "content": "Odvetniki lahko zaračunavajo po odvetniški tarifi (točkovni sistem), po urni postavki ali s pavšalnim zneskom za celotno zadevo. Način obračunavanja se dogovorite vnaprej."},
    {"type": "heading", "content": "Koliko stane prvi posvet pri odvetniku?"},
    {"type": "paragraph", "content": "Prvi posvet pri odvetniku je pogosto kratko, 30 do 60 minutno srečanje, na katerem odvetniku predstavite svoj problem. Odvetnik vam poda prvo mnenje in oceni vaše možnosti."},
    {"type": "list", "content": "Okvirne cene prvega posveta:", "items": ["Telefonski posvet (15-30 min): 30-80 EUR", "Osebni posvet (30 min): 50-100 EUR", "Osebni posvet (60 min): 80-150 EUR", "Pisno pravno mnenje: 150-500 EUR"]},
    {"type": "paragraph", "content": "Nekateri odvetniki ponujajo brezplačen prvi posvet, da ocenijo zadevo. Vedno vprašajte vnaprej, ali je prvi posvet plačljiv."},
    {"type": "heading", "content": "Koliko stane odvetnik za ločitev?"},
    {"type": "paragraph", "content": "Stroški ločitve so odvisni predvsem od tega, ali gre za sporazumno ali sporno ločitev. Sporazumna ločitev je bistveno cenejša in hitrejša."},
    {"type": "list", "content": "Cene odvetnika za ločitev:", "items": ["Sporazumna ločitev (brez otrok): 400-1.000 EUR", "Sporazumna ločitev (z otroki): 600-1.500 EUR", "Sporna ločitev: 2.000-5.000+ EUR", "Sporna ločitev z delitvijo premoženja: 3.000-10.000+ EUR", "Dogovor o preživnini: 500-2.000 EUR"]},
    {"type": "heading", "content": "Koliko stane odvetnik za dedovanje?"},
    {"type": "paragraph", "content": "Pri dedovanju so stroški odvisni od zahtevnosti zapuščinskega postopka in ali gre za sporno ali nespornospornost med dediči."},
    {"type": "list", "content": "Cene odvetnika za dedovanje:", "items": ["Zastopanje v zapuščinskem postopku: 500-2.000 EUR", "Sestava oporoke: 150-400 EUR", "Izpodbijanje oporoke: 2.000-5.000+ EUR", "Dedni dogovor med dediči: 300-1.000 EUR", "Uveljavljanje nujnega deleža: 1.500-4.000 EUR"]},
    {"type": "heading", "content": "Koliko stane sestavitev pogodbe?"},
    {"type": "paragraph", "content": "Sestavitev pogodbe je ena najpogostejših odvetniških storitev. Cena je odvisna od vrste in zahtevnosti pogodbe."},
    {"type": "list", "content": "Cene za sestavitev pogodb:", "items": ["Kupoprodajna pogodba za nepremičnino: 300-1.000 EUR", "Najemna pogodba: 150-400 EUR", "Darilna pogodba: 200-500 EUR", "Pogodba o zaposlitvi: 200-500 EUR", "Menjalna pogodba: 200-600 EUR", "Pogodba o dosmrtnem preživljanju: 300-800 EUR", "Pregled obstoječe pogodbe: 100-300 EUR"]},
    {"type": "heading", "content": "Koliko stane zastopanje na sodišču?"},
    {"type": "list", "content": "Cene za zastopanje na sodišču:", "items": ["Priprava tožbe: 300-1.000 EUR", "Zastopanje na naroku: 200-500 EUR/narok", "Celoten pravdni postopek (preprostejši): 1.500-3.000 EUR", "Celoten pravdni postopek (zahtevnejši): 3.000-10.000+ EUR", "Delovno pravo (spor z delodajalcem): 1.000-4.000 EUR"]},
    {"type": "heading", "content": "Kako prihraniti pri pravnem svetovanju?"},
    {"type": "list", "content": "Nasveti za nižje stroške:", "items": ["Pripravite se na posvet -- organizirajte dokumente in zapišite vprašanja vnaprej", "Vprašajte za oceno stroškov pred začetkom -- odvetnik vam mora podati predračun", "Preverite ali ste upravičeni do brezplačne pravne pomoči (BPP)", "Za orientacijo uporabite AI pravnega pomočnika -- dobite takojšnji nasvet brezplačno", "Primerjajte ponudbe več odvetnikov za isto zadevo", "Za enostavne zadeve preverite ali zadostuje pisni pravni nasvet namesto zastopanja"]},
    {"type": "cta", "content": "Preden obiščete odvetnika, preizkusite AI-Odvetnika brezplačno. Dobite takojšnji pravni nasvet in oceno vaše situacije -- tako boste bolje pripravljeni na posvet z odvetnikom."},
    {"type": "heading", "content": "AI pravna pomoč kot cenovno dostopna alternativa"},
    {"type": "paragraph", "content": "Za mnoga pravna vprašanja ne potrebujete takoj odvetnika. AI pravni pomočnik vam lahko pomaga razumeti vaše pravice, oceniti situacijo in se pripraviti na morebitni posvet z odvetnikom. To je še posebej koristno za orientacijo pri preprostejših zadevah, kot so pravice najemnika, reklamacije, delovnopravna vprašanja ali razumevanje pogodb."},
    {"type": "paragraph", "content": "AI-Odvetnik je na voljo 24/7, odgovor dobite v minutah, osnovni paket pa je brezplačen. Za zahtevnejše pravne zadeve pa vsekakor priporočamo posvet z licenciranim odvetnikom."},
    {"type": "heading", "content": "Zaključek"},
    {"type": "paragraph", "content": "Cene odvetnikov v Sloveniji se gibljejo od 50 EUR za kratek posvet do več tisoč evrov za zahtevne pravdne postopke. Ključno je, da stroške preverite vnaprej, se dobro pripravite na posvet in za orientacijo uporabite dostopne vire, kot je AI pravna pomoč. Tako boste prihranili čas in denar, hkrati pa zaščitili svoje pravice."}
  ]'::jsonb
);

-- Article 3: Kako napisati oporoko
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'kako-napisati-oporoko-vodic',
  'Kako napisati oporoko — praktičen vodič po korakih za 2026',
  'Vodič za pisanje veljavne oporoke v Sloveniji: lastnoročna oporoka, notarska oporoka, nujni delež, pogosti napake in kako se jim izogniti.',
  'Dedovanje',
  ARRAY[
    'kako napisati oporoko',
    'kako napisati veljavno oporoko',
    'kako napisati lastnoročno oporoko',
    'kako pravilno napisati oporoko',
    'oporoka vzorec',
    'oporoka primer',
    'lastnoročna oporoka',
    'notarska oporoka',
    'nujni delež',
    'nujni delež pri dedovanju',
    'dedovanje',
    'dedovanje nepremičnine',
    'zapuščinski postopek',
    'kdo so dediči prvega dednega reda',
    'izpodbijanje oporoke',
    'kako se odpovedati dediščini',
    'oporoka slovenija'
  ],
  '9 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Oporoka je dokument, s katerim določite, kako se bo vaše premoženje razdelilo po vaši smrti. Brez oporoke se premoženje razdeli po zakonitem dednem redu, kar pogosto ne ustreza željam zapustnika. V tem vodiču vam razložimo, kako napisati veljavno oporoko v Sloveniji, katere oblike oporok poznamo in na katere pasti morate paziti."},
    {"type": "heading", "content": "Zakaj napisati oporoko?"},
    {"type": "paragraph", "content": "Mnogi menijo, da oporoko potrebujejo samo premožni ljudje. To ne drži. Oporoka je smiselna za vsakogar, ki želi sam odločiti, komu bo zapustil svoje premoženje -- pa naj gre za nepremičnino, prihranke, osebne predmete ali naložbe."},
    {"type": "list", "content": "Razlogi za pisanje oporoke:", "items": ["Želite zapustiti premoženje osebi, ki ni vaš zakoniti dedič", "Želite neenakomerno razdeliti premoženje med dediče", "Imate partnerja, s katerim niste poročeni", "Želite del premoženja zapustiti dobrodelni organizaciji", "Želite preprečiti spore med dediči", "Imate podjetje, ki ga želite prenesti na določeno osebo"]},
    {"type": "heading", "content": "Vrste oporok v Sloveniji"},
    {"type": "paragraph", "content": "Obligacijski zakonik (OZ) in Zakon o dedovanju (ZD) poznata več oblik oporok. Najpogostejše so:"},
    {"type": "list", "content": "Oblike oporok:", "items": ["Lastnoročna (holografska) oporoka -- napisana v celoti z lastno roko, datirana in podpisana", "Pisna oporoka pred pričami (alografska) -- vnaprej pripravljena, podpisana pred dvema pričama", "Sodna oporoka -- sestavljena na sodišču z zapisnikom", "Notarska oporoka -- sestavljena pri notarju, ki poskrbi za pravilnost", "Ustna oporoka -- samo v izjemnih okoliščinah (smrtna nevarnost), veljavna le 30 dni po prenehanju okoliščin"]},
    {"type": "heading", "content": "Kako napisati lastnoročno oporoko -- korak za korakom"},
    {"type": "paragraph", "content": "Lastnoročna oporoka je najpreprostejša in najpogostejša oblika. Zanjo ne potrebujete odvetnika ali notarja, vendar morate upoštevati stroge zahteve, da bo veljavna."},
    {"type": "list", "content": "Zahteve za veljavno lastnoročno oporoko:", "items": ["Celotno besedilo mora biti napisano z LASTNO ROKO (ne na računalniku ali pisalnem stroju)", "Mora vsebovati DATUM (dan, mesec, leto)", "Mora biti PODPISANA z vašim imenom in priimkom", "Priporočljivo je navesti kraj pisanja", "Priče NISO potrebne (a so priporočljive za dodatno varnost)"]},
    {"type": "list", "content": "Koraki za pisanje:", "items": ["1. Vzemite čist list papirja in pisalo", "2. Na vrh zapišite: OPOROKA", "3. Zapišite datum in kraj: V Ljubljani, dne 23. marca 2026", "4. Zapišite: Jaz, [polno ime], rojen/a [datum rojstva], stanujoč/a na [naslov], v polni poslovni sposobnosti določam:", "5. Navedite, komu zapuščate posamezne stvari ali deleže premoženja", "6. Določite morebitnega izvršitelja oporoke", "7. Na koncu se podpišite s polnim imenom in priimkom"]},
    {"type": "heading", "content": "Kaj je nujni delež?"},
    {"type": "paragraph", "content": "Nujni delež je del zapuščine, ki pripada določenim dedičem ne glede na vsebino oporoke. Z oporoko ga ne morete v celoti izključiti. Nujni dediči so: potomci (otroci, vnuki), zakonec/partner in starši zapustnika."},
    {"type": "list", "content": "Višina nujnega deleža:", "items": ["Potomci in zakonec: 1/2 zakonitega dednega deleža", "Starši zapustnika: 1/3 zakonitega dednega deleža", "Primer: Če imate zakonca in dva otroka, bi vsak po zakonu dedoval 1/3. Nujni delež vsakega je torej 1/6 celotne zapuščine."]},
    {"type": "heading", "content": "Pogoste napake pri pisanju oporoke"},
    {"type": "list", "content": "Napake, ki lahko povzročijo neveljavnost:", "items": ["Oporoka ni v celoti lastnoročno napisana (npr. natisnjena na računalniku)", "Manjka datum ali podpis", "Nejasne ali dvoumne določbe (npr. zapuščam svojo hišo Marku -- katera hiša? Kateri Marko?)", "Pozabljen nujni delež -- dediči ga lahko uveljavljajo na sodišču", "Pisanje oporoke pod pritiskom ali v stanju, ko oseba ni poslovno sposobna", "Oporoka ni shranjena na varnem mestu ali nihče ne ve zanjo"]},
    {"type": "heading", "content": "Kje shraniti oporoko?"},
    {"type": "list", "content": "Možnosti shranjevanja:", "items": ["Pri notarju -- najvarnejša možnost, notar jo vpiše v register oporok", "V sefuv banki", "Doma na varnem mestu -- povejte zaupanja vredni osebi, kje se nahaja", "Na sodišču -- nekatera sodišča omogočajo shranjevanje"]},
    {"type": "heading", "content": "Kdaj potrebujete odvetnika za oporoko?"},
    {"type": "paragraph", "content": "Za preprosto lastnoročno oporoko odvetnik ni potreben. Vendar je strokovna pomoč priporočljiva v naslednjih primerih:"},
    {"type": "list", "content": "Kdaj k odvetniku:", "items": ["Imate obsežno ali zapleteno premoženje (podjetje, nepremičnine v tujini)", "Želite izključiti zakonitega dediča (morate upoštevati nujni delež)", "Imate dediče v različnih državah", "Želite ustanoviti skrbniški sklad ali določiti posebne pogoje", "Želite spremeniti ali preklicati obstoječo oporoko"]},
    {"type": "cta", "content": "Imate vprašanje o dedovanju ali oporoki? Vprašajte AI-Odvetnika brezplačno in dobite takojšnji odgovor o vaših pravicah."},
    {"type": "heading", "content": "Zaključek"},
    {"type": "paragraph", "content": "Pisanje oporoke ni zapleteno, če upoštevate zakonske zahteve. Lastnoročna oporoka je najlažja pot -- potrebujete le papir, pisalo in jasno voljo. Pazite na nujni delež, bodite natančni pri opisovanju premoženja in dedičev ter shranite oporoko na varno mesto. Če imate kakršnakoli dvom, se posvetujte s strokovnjakom."}
  ]'::jsonb
);

-- Article 4: Odpoved pogodbe o zaposlitvi
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'odpoved-pogodbe-o-zaposlitvi-pravice-in-postopek',
  'Odpoved pogodbe o zaposlitvi — vaše pravice in celoten postopek',
  'Vse o odpovedi pogodbe o zaposlitvi v Sloveniji: redna in izredna odpoved, odpovedni rok, odpravnina, pravice delavca in delodajalca ter kaj storiti ob nezakoniti odpovedi.',
  'Delovno pravo',
  ARRAY[
    'odpoved pogodbe o zaposlitvi',
    'odpoved pogodbe o zaposlitvi vzorec',
    'odpoved pogodbe o zaposlitvi s strani delavca',
    'odpoved pogodbe o zaposlitvi s strani delodajalca',
    'odpoved pogodbe o zaposlitvi iz poslovnega razloga',
    'izredna odpoved pogodbe o zaposlitvi',
    'odpoved pogodbe s ponudbo nove',
    'odpovedni rok',
    'odpovedni rok koliko traja',
    'odpravnina',
    'odpravnina izračun',
    'pravice delavca ob odpovedi',
    'pravna pomoč delovno pravo',
    'mobing na delovnem mestu',
    'nezakonita odpoved',
    'delovno pravo',
    'pogodba o zaposlitvi'
  ],
  '10 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Odpoved pogodbe o zaposlitvi je ena najpogostejših in najstresnejših pravnih situacij, s katero se srečajo zaposleni v Sloveniji. Ne glede na to, ali odpovedujete sami ali ste prejeli odpoved od delodajalca, je ključno, da poznate svoje pravice. V tem vodiču vam razložimo vse oblike odpovedi, odpovedne roke, odpravnine in kaj storiti, če menite, da je bila odpoved nezakonita."},
    {"type": "heading", "content": "Vrste odpovedi pogodbe o zaposlitvi"},
    {"type": "paragraph", "content": "Zakon o delovnih razmerjih (ZDR-1) pozna več načinov prenehanja pogodbe o zaposlitvi. Najpomembnejše so:"},
    {"type": "list", "content": "Načini prenehanja:", "items": ["Redna odpoved -- z odpovednim rokom, možna tako s strani delavca kot delodajalca", "Izredna odpoved -- brez odpovednega roka, samo v zakonsko določenih primerih", "Sporazumna razveljavitev -- obe strani se dogovorita za prenehanje", "Potek pogodbe za določen čas -- avtomatično prenehanje ob izteku"]},
    {"type": "heading", "content": "Odpoved s strani delavca"},
    {"type": "paragraph", "content": "Kot delavec lahko kadar koli redno odpoveste pogodbo o zaposlitvi. Ne potrebujete navesti razloga. Upoštevati morate le odpovedni rok."},
    {"type": "list", "content": "Pravila za delavčevo odpoved:", "items": ["Odpoved mora biti v pisni obliki", "Ne potrebujete navesti razloga", "Odpovedni rok: 15 dni (če ni s pogodbo ali kolektivno pogodbo določen daljši rok, a največ 30 dni)", "V odpovednem roku morate normalno opravljati delo", "Nimate pravice do odpravnine"]},
    {"type": "heading", "content": "Odpoved s strani delodajalca"},
    {"type": "paragraph", "content": "Delodajalec lahko redno odpove pogodbo o zaposlitvi samo iz utemeljenih razlogov, ki jih določa zakon:"},
    {"type": "list", "content": "Zakoniti razlogi za odpoved:", "items": ["Poslovni razlog -- ukinitev delovnega mesta, reorganizacija, zmanjšan obseg dela", "Razlog nesposobnosti -- delavec ne dosega pričakovanih rezultatov", "Krivdni razlog -- kršitev obveznosti iz pogodbe o zaposlitvi (po predhodnem opozorilu)", "Nezmožnost za delo -- invalidnost ali zdravstveni razlogi (s posebnimi pogoji)"]},
    {"type": "heading", "content": "Odpoved iz poslovnega razloga"},
    {"type": "paragraph", "content": "Najpogostejši razlog za odpoved s strani delodajalca. Pri odpovedi iz poslovnega razloga mora delodajalec upoštevati:"},
    {"type": "list", "content": "Obveznosti delodajalca:", "items": ["Pisna odpoved z navedbo razloga", "Preveriti možnost zaposlitve na drugem delovnem mestu (odpoved s ponudbo nove pogodbe)", "Upoštevati odpovedni rok", "Izplačati odpravnino", "Prijaviti delavca na Zavod za zaposlovanje"]},
    {"type": "heading", "content": "Koliko traja odpovedni rok?"},
    {"type": "paragraph", "content": "Dolžina odpovednega roka je odvisna od trajanja zaposlitve pri delodajalcu:"},
    {"type": "list", "content": "Odpovedni roki pri odpovedi s strani delodajalca:", "items": ["Do 1 leta zaposlitve: 15 dni", "Od 1 do 2 leti: 30 dni", "Od 2 do 5 let: 30 dni", "Od 5 do 15 let: 60 dni", "Od 15 do 25 let: 80 dni", "Nad 25 let: 150 dni"]},
    {"type": "heading", "content": "Odpravnina — koliko vam pripada?"},
    {"type": "paragraph", "content": "Ob odpovedi iz poslovnega razloga ali razloga nesposobnosti vam pripada odpravnina. Višina je odvisna od časa zaposlitve:"},
    {"type": "list", "content": "Višina odpravnine:", "items": ["Do 5 let zaposlitve: 1/5 osnove za vsako leto dela", "Od 5 do 15 let: 1/4 osnove za vsako leto dela", "Nad 15 let: 1/3 osnove za vsako leto dela", "Osnova za izračun: povprečna mesečna plača delavca v zadnjih 3 mesecih", "Odpravnina ne sme presegati 10-kratnika osnove"]},
    {"type": "heading", "content": "Izredna odpoved pogodbe o zaposlitvi"},
    {"type": "paragraph", "content": "Izredna odpoved pomeni takojšnje prenehanje delovnega razmerja brez odpovednega roka. Možna je tako s strani delavca kot delodajalca, a le v zakonsko določenih primerih."},
    {"type": "list", "content": "Kdaj lahko delavec izredno odpove:", "items": ["Delodajalec več kot 2 meseca ne izplačuje plače ali prispevkov", "Delodajalec ni zagotovil varnosti in zdravja pri delu", "Delodajalec ni omogočil dela -- delavec je bil odsoten več kot 30 dni", "Delodajalec je poniževal ali nasilno ravnal z delavcem (mobing)"]},
    {"type": "list", "content": "Kdaj lahko delodajalec izredno odpove:", "items": ["Hujša kršitev obveznosti z znaki kaznivega dejanja", "Naklepno ali iz hude malomarnosti povzročena škoda", "Kršitev poslovne skrivnosti", "Odsotnost z dela 5 ali več zaporednih dni brez obvestila", "Delo pod vplivom alkohola ali drog kljub opozorilu"]},
    {"type": "heading", "content": "Kaj storiti ob nezakoniti odpovedi?"},
    {"type": "paragraph", "content": "Če menite, da je bila vaša odpoved nezakonita, imate pravico do pravnega varstva:"},
    {"type": "list", "content": "Koraki ob nezakoniti odpovedi:", "items": ["1. V 30 dneh od prejema odpovedi zahtevajte razveljavitev pri delodajalcu", "2. Če delodajalec zavrne, imate 30 dni za vložitev tožbe na delovno sodišče", "3. Zahtevate lahko vrnitev na delo ali odškodnino", "4. Preverite upravičenost do brezplačne pravne pomoči (BPP)", "5. Vpišite se na Zavod za zaposlovanje za prejemanje nadomestila za brezposelnost"]},
    {"type": "quote", "content": "Roki so kratki! Od prejema odpovedi imate le 30 dni za vložitev zahteve za razveljavitev pri delodajalcu. Ne odlašajte s pravnim ukrepanjem."},
    {"type": "cta", "content": "Ste prejeli odpoved pogodbe o zaposlitvi? Preverite vaše pravice z AI-Odvetnikom brezplačno in ugotovite, ali je bila odpoved zakonita."},
    {"type": "heading", "content": "Zaključek"},
    {"type": "paragraph", "content": "Odpoved pogodbe o zaposlitvi je resen pravni akt z jasno določenimi pravili za obe strani. Kot delavec imate pravico do odpovednega roka, odpravnine (pri odpovedi iz poslovnega razloga) in pravnega varstva ob nezakoniti odpovedi. Ključno je, da poznate svoje pravice in ukrepate pravočasno — roki za izpodbijanje odpovedi so kratki."}
  ]'::jsonb
);

-- Article 5: Razveza zakonske zveze
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'razveza-zakonske-zveze-postopek-stroski',
  'Razveza zakonske zveze — postopek, stroški in pravna pomoč',
  'Celoten vodič o ločitvi v Sloveniji: sporazumna in sporna razveza, delitev premoženja, preživnina, skrbništvo otrok, stroški in pravna pomoč.',
  'Družinsko pravo',
  ARRAY[
    'razveza zakonske zveze',
    'razveza zakonske zveze postopek',
    'sporazumna razveza',
    'sporazumna razveza postopek',
    'ločitev',
    'ločitev postopek',
    'koliko stane ločitveni postopek',
    'koliko stane ločitev',
    'ločitev in delitev premoženja',
    'preživnina',
    'preživnina izračun',
    'pravna pomoč razveza',
    'kako se sporazumno razvezati',
    'odvetnik za ločitev',
    'stiki z otrokom po ločitvi',
    'skrbništvo otrok',
    'skupno premoženje zakoncev'
  ],
  '9 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Razveza zakonske zveze je čustveno in pravno zahteven proces. V Sloveniji se letno razveže okrog 2.500 zakonskih zvez. Ne glede na to, ali se razvezujete sporazumno ali je pred vami sporen postopek, je pomembno, da razumete celoten proces, vaše pravice in obveznosti. V tem vodiču vam razložimo vse, kar morate vedeti o ločitvi v Sloveniji."},
    {"type": "heading", "content": "Sporazumna razveza zakonske zveze"},
    {"type": "paragraph", "content": "Sporazumna razveza je najhitrejša, najcenejša in najmanj stresna oblika ločitve. Mogoča je, kadar se zakonca dogovorita o vseh bistvenih vprašanjih: delitvi premoženja, preživnini in — če imata otroke — o skrbništvu in stikih."},
    {"type": "list", "content": "Postopek sporazumne razveze:", "items": ["1. Zakonca sestavita sporazum o razvezi (lahko s pomočjo odvetnika ali mediatorja)", "2. Sporazum mora vsebovati: delitev skupnega premoženja, dogovor o preživnini, dogovor o skrbništvu in stikih z otroki", "3. Predlog za sporazumno razvezo vložita na pristojno sodišče", "4. Sodišče razpiše narok (obravnavo)", "5. Sodnik preveri, ali je sporazum v skladu z zakonom in v korist otrok", "6. Sodišče izda sodbo o razvezi"]},
    {"type": "paragraph", "content": "Celoten postopek sporazumne razveze običajno traja 1-3 mesece."},
    {"type": "heading", "content": "Sporna razveza zakonske zveze"},
    {"type": "paragraph", "content": "Kadar se zakonca ne moreta dogovoriti, sledi sporna razveza. Sodišče odloča o vseh spornih vprašanjih. Postopek je daljši, dražji in bolj stresen."},
    {"type": "list", "content": "Postopek sporne razveze:", "items": ["1. Eden od zakoncev vloži tožbo za razvezo na pristojno sodišče", "2. Sodišče napoti zakonca na mediacijao (obvezno)", "3. Če mediacija ne uspe, sodišče začne pravdni postopek", "4. Obravnave in dokazovanje", "5. Sodišče odloči o razvezi, premoženju, preživnini in otrocih", "6. Možnost pritožbe na višje sodišče"]},
    {"type": "paragraph", "content": "Sporna razveza lahko traja od 6 mesecev do več let, odvisno od zahtevnosti."},
    {"type": "heading", "content": "Delitev skupnega premoženja"},
    {"type": "paragraph", "content": "Skupno premoženje je vse, kar sta zakonca pridobila med trajanjem zakonske zveze z delom ali odplačno. Posebno premoženje (dediščina, darila, premoženje pred poroko) ostane ločena last."},
    {"type": "list", "content": "Pravila delitve:", "items": ["Domneva je, da sta deleža enaka (50:50)", "Zakonec lahko dokaže, da je prispeval več, in zahteva večji delež", "Delitev vključuje: nepremičnine, vozila, prihranke, naložbe, podjetja", "Dolgovi iz skupnega premoženja se delijo sorazmerno", "Zakonca se lahko o delitvi dogovorita sama ali odloči sodišče"]},
    {"type": "heading", "content": "Preživnina"},
    {"type": "paragraph", "content": "Preživnina je lahko zakonska (med bivšima zakoncema) ali otroška (za vzdrževanje otrok)."},
    {"type": "list", "content": "Zakonska preživnina:", "items": ["Pripada zakoncu, ki nima sredstev za preživljanje in ni zaposlen brez lastne krivde", "Običajno začasna (do zaposlitve ali pridobitve novih sredstev)", "Višina je odvisna od potreb upravičenca in zmožnosti zavezanca"]},
    {"type": "list", "content": "Otroška preživnina:", "items": ["Obvezna za roditelja, ki nima skrbništva (ali ima manjši delež)", "Minimalna preživnina znaša okrog 130 EUR/mesec na otroka", "Višina je odvisna od potreb otroka in dohodkov obeh staršev", "Plačuje se do otrokovega 18. leta (ali do 26. leta, če se redno šola)"]},
    {"type": "heading", "content": "Skrbništvo otrok in stiki"},
    {"type": "paragraph", "content": "Pri razvezi z otroki je najpomembnejša korist otroka. Sodišče vedno odloča v skladu s tem načelom."},
    {"type": "list", "content": "Možnosti:", "items": ["Skupno skrbništvo -- otroka vzgajata oba starša skupaj (najpogostejše pri sporazumni razvezi)", "Eno skrbništvo -- otrok živi pri enem staršu, drugi ima pravico do stikov", "Stiki se določijo konkretno: dnevi, vikendi, počitnice, prazniki", "Sodišče lahko odredi tudi strokovno mnenje centra za socialno delo"]},
    {"type": "heading", "content": "Koliko stane ločitev?"},
    {"type": "list", "content": "Okvirni stroški:", "items": ["Sporazumna razveza z odvetnikom: 500-1.500 EUR", "Sporna razveza: 2.000-5.000+ EUR (odvisno od trajanja)", "Sodna taksa za razvezo: okrog 200-400 EUR", "Mediacija: 100-300 EUR/srečanje", "Cenitev premoženja (če potrebna): 300-1.000 EUR"]},
    {"type": "cta", "content": "Razmišljate o ločitvi in ne veste, kje začeti? Vprašajte AI-Odvetnika brezplačno o svojih pravicah in možnostih."},
    {"type": "heading", "content": "Zaključek"},
    {"type": "paragraph", "content": "Razveza zakonske zveze je zahteven proces, a z dobro pripravo in poznavanjem pravic ga lahko opravite brez nepotrebnega stresa. Sporazumna razveza je vedno boljša izbira -- je hitrejša, cenejša in manj obremenjujoča, še posebej za otroke. Če sporazum ni mogoč, pa ne odlašajte s pravno pomočjo -- vaše pravice imajo roke, ki jih morate upoštevati."}
  ]'::jsonb
);

-- Article 6: AI pravna pomoč
INSERT INTO blog_posts (slug, title, description, category, keywords, reading_time, published, published_at, content)
VALUES (
  'ai-pravna-pomoc-umetna-inteligenca-pravo',
  'AI pravna pomoč — kako umetna inteligenca pomaga pri pravnih vprašanjih',
  'Kako AI odvetnik in umetna inteligenca spreminjata dostop do pravne pomoči v Sloveniji. Prednosti, omejitve in praktični primeri uporabe AI pravnega pomočnika.',
  'Tehnologija',
  ARRAY[
    'AI odvetnik',
    'AI pravna pomoč',
    'umetna inteligenca pravo',
    'umetna inteligenca odvetnik',
    'pravni pomočnik AI',
    'AI pravnik',
    'AI pravnik slovenija',
    'pravna pomoč online',
    'odvetnik online',
    'pravni nasvet online',
    'brezplačna pravna pomoč',
    'pravni nasvet brezplačno',
    'digitalna pravna pomoč',
    'chatbot pravna pomoč',
    'AI za odvetnike',
    'prihodnost prava'
  ],
  '7 min',
  true,
  now(),
  '[
    {"type": "paragraph", "content": "Umetna inteligenca spreminja številne panoge — in pravo ni izjema. V Sloveniji je dostop do pravne pomoči pogosto omejen z visokimi stroški odvetnikov in dolgimi čakalnimi dobami. AI pravni pomočniki, kot je AI-Odvetnik, odpirajo povsem nov način dostopa do pravnih informacij: takojšen, dostopen in cenovno ugoden."},
    {"type": "heading", "content": "Kaj je AI pravni pomočnik?"},
    {"type": "paragraph", "content": "AI pravni pomočnik je aplikacija, ki uporablja napredno umetno inteligenco za odgovarjanje na pravna vprašanja. Za razliko od preprostih chatbotov, ki delujejo na podlagi vnaprej pripravljenih odgovorov, AI pravni pomočnik razume kontekst vašega vprašanja, analizira relevantno zakonodajo in vam poda prilagojen odgovor."},
    {"type": "list", "content": "Kaj AI pravni pomočnik zmore:", "items": ["Razumevanje naravnega jezika -- vprašanje postavite z lastnimi besedami", "Analiza konkretne situacije -- upošteva podrobnosti vašega primera", "Poznavanje slovenske zakonodaje -- ZDR-1, OZ, Zakon o dedovanju, ZPP in drugi", "Pojasnjevanje pravnih postopkov -- koraki, roki, potrebni dokumenti", "Ocena pravic in možnosti -- kaj lahko storite v vaši situaciji", "Priporočila za nadaljnje korake -- kdaj potrebujete odvetnika"]},
    {"type": "heading", "content": "Kdaj uporabiti AI pravno pomoč?"},
    {"type": "paragraph", "content": "AI pravni pomočnik je idealen za širok nabor situacij, še posebej ko potrebujete hitro orientacijo ali pa ne veste, ali sploh potrebujete odvetnika."},
    {"type": "list", "content": "Najpogostejši primeri uporabe:", "items": ["Pravice najemnika ali najemodajalca -- kaj lahko zahtevam? Koliko je odpovedni rok?", "Delovno pravo -- ali je moja odpoved zakonita? Kakšna odpravnina mi pripada?", "Dedovanje -- kdo deduje? Kaj je nujni delež? Kako napisati oporoko?", "Potrošniške pravice -- reklamacija, garancija, vračilo kupnine", "Ločitev -- kako poteka postopek? Koliko stane? Kaj z otroki?", "Pogodbe -- pregled pogodbe, razumevanje pogojev, pravice ob kršitvi", "Prometne nesreče -- odškodnina, prijava, zavarovalnica", "Sosedski spori -- hrup, meja, drevo, pravica dostopa"]},
    {"type": "heading", "content": "Prednosti AI pravne pomoči"},
    {"type": "list", "content": "Zakaj AI pravni pomočnik?", "items": ["Takojšen odgovor -- ni čakanja na termin, odgovor v minutah", "Dostopnost 24/7 -- tudi ponoči, ob vikendih in praznikih", "Cenovno dostopno -- osnovni paket brezplačen, plačljivi paketi bistveno cenejši od odvetnika", "Brez zadržkov -- lažje je vprašati AI kot prvič poklicati odvetnika", "Priprava na posvet -- razumete situacijo, preden obiščete odvetnika", "Zasebnost -- vaše vprašanje ostane zaupno"]},
    {"type": "heading", "content": "Omejitve AI pravne pomoči"},
    {"type": "paragraph", "content": "Pomembno je razumeti, da AI pravni pomočnik ni nadomestek za odvetnika. Obstajajo situacije, ko nujno potrebujete pravega pravnega strokovnjaka."},
    {"type": "list", "content": "Kdaj potrebujete pravega odvetnika:", "items": ["Zastopanje pred sodiščem -- AI vas ne more zastopati na naroku", "Sestavitev pravno zavezujočih dokumentov -- pogodbe, tožbe, oporoke (za preverjanje veljavnosti)", "Zapletene zadeve z visokim tveganjem -- kazenske zadeve, visoki odškodninski zahtevki", "Pogajanja z nasprotno stranko -- mediacija, poravnave", "Nujni roki -- če vam teče rok za vložitev tožbe ali pritožbe"]},
    {"type": "quote", "content": "AI pravni pomočnik je kot navigacija -- pokaže vam pot in možnosti, a volana morate držati sami. Za zahtevne situacije pa potrebujete izkušenega šoferja."},
    {"type": "heading", "content": "Kako deluje AI-Odvetnik?"},
    {"type": "list", "content": "Postopek v 3 korakih:", "items": ["1. Izberite pravno področje (dedovanje, delo, družina, nepremičnine...)", "2. Opišite svojo situacijo z lastnimi besedami", "3. Prejmite prilagojen pravni nasvet z razlago vaših pravic in možnih korakov"]},
    {"type": "paragraph", "content": "AI-Odvetnik je zasnovan posebej za slovensko pravo in slovensko zakonodajo. Razume slovenščino in vam odgovori v razumljivem jeziku, brez pravniškega žargona."},
    {"type": "heading", "content": "AI pravna pomoč v Sloveniji — stanje in prihodnost"},
    {"type": "paragraph", "content": "Slovenija sledi svetovnim trendom digitalizacije pravnih storitev. AI pravni pomočniki postajajo vse bolj natančni in zmožni. V prihodnosti lahko pričakujemo:"},
    {"type": "list", "content": "Trendi:", "items": ["Avtomatsko generiranje pravnih dokumentov (pogodbe, dopisi, pritožbe)", "Povezava z uradnimi bazami podatkov (sodna praksa, zakonodaja)", "Proaktivno opozarjanje na pravne roke in spremembe zakonodaje", "Integracija z e-upravo za lažje vlaganje vlog"]},
    {"type": "cta", "content": "Preizkusite AI-Odvetnika brezplačno in se prepričajte, kako vam lahko umetna inteligenca pomaga pri vašem pravnem vprašanju."},
    {"type": "heading", "content": "Zaključek"},
    {"type": "paragraph", "content": "AI pravna pomoč ne nadomešča odvetnikov, temveč dopolnjuje dostop do pravnih informacij. Za mnoge Slovence, ki si ne morejo privoščiti odvetnika ali pa ne vedo, kje začeti, je AI pravni pomočnik prva in najpomembnejša stopnica do razumevanja njihovih pravic. Bodočnost je v kombinaciji človeškega strokovnega znanja in zmožnosti umetne inteligence."}
  ]'::jsonb
);
